env:
  - NODE_VERSION=0.10
  - NODE_VERSION=0.11
#  - NODE_VERSION=iojs

os:
  - linux
  - osx

install:
  - test $TRAVIS_OS_NAME = "osx" && brew install nvm && source $(brew --prefix nvm)/nvm.sh || test $TRAVIS_OS_NAME = "linux"
  - nvm install $NODE_VERSION
  - node --version
  - npm --version
  - npm install

script:
  - npm test

matrix:
  allow_failures:
    - env: "NODE_VERSION=0.11"
    - env: "NODE_VERSION=iojs"
  fast_finish: true
